newsapp/urls.py
from django.contrib import admin
from django.urls import path
from newsapp import views
from django.contrib.auth import views as auth_views

from newsapp.form import LoginForm

urlpatterns = [
   path('',views.home,name="home"),
   path('about/',views.about,name="about"),
   path('contact/',views.contact,name="contact"),
   path('dashbord/',views.dashbord,name="dashbord"),
   path('login/',auth_views.LoginView.as_view(template_name='blog/login.html',form_class=LoginForm),name="login"),
   path('signup/',views.signup,name="signup"),
   path('logout/',auth_views.LogoutView.as_view(),name="logout"),
   path('edit/<int:id>/',views.edit,name='edit'),
   path('delete/<int:id>/',views.delete,name='delete'),
   path('addpost/',views.add_post,name="addpost")
   
#    path('registration/',views.Registrationview.as_view(),name="registration")
]

newsblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls'))
]

newsapp/models.py
from django.db import models

# Create your models here
class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    
class Contact(models.Model):
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    message = models.CharField(max_length=100)

newsapp/views.py
from tokenize import group
from django import forms
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.views import View
from .form import SignupForm,PostForm,ContactForm
from .models import Contact, Post
from django.contrib.auth.models import Group
# from .form import RegistrationForm

# Create your views here.
# home
def home(request):
  posts = Post.objects.all()
  return render(request,'blog/home.html',{'posts':posts})
# about
def about(request):
  return render(request,'blog/about.html')  

# contact
def contact(request):
  if request.method == "POST":
     form=ContactForm(request.POST)
     if form.is_valid():
      name=form.cleaned_data['name']
      password=form.cleaned_data['password']
      address = form.cleaned_data['address']
      message = form.cleaned_data['message']
      cont = Contact(name=name,password=password,address=address,message=message)
      cont.save()
      form=ContactForm()  
  else:
    form=ContactForm()  
  return render(request,'blog/contact.html',{'form':form})
    
# dashboard
def dashbord(request):
  if request.user.is_authenticated:
   posts = Post.objects.all()
   user=request.user
   full_name=user.get_full_name()
   gps=user.groups.all()
   return render(request,'blog/dashbord.html',{'posts':posts,'user':user,'full_name':full_name,'groups':gps})
  else:
   return HttpResponseRedirect("login/")
  
# logout
def logout(request):  
    return redirect(request,'blog/login.html')
  
  
# signup
def signup(request):
  if request.method == "POST":
    form=SignupForm(request.POST)
    if form.is_valid():
     messages.success(request,"Congratulation, You have successfully Registered !!")
     user=form.save()
     group=Group.objects.get(name='Author')
     user.groups.add(group)              
  else:
    form=SignupForm()     
  return render(request,'blog/signup.html',{'form':form})


# edit
def edit(request,id):
  if request.user.is_authenticated:
    if request.method=='POST':
     update=Post.objects.get(pk=id)
     form=PostForm(request.POST,instance=update)
     if form.is_valid():
       form.save()

    else: 
      update=Post.objects.get(pk=id)
      form=PostForm(instance=update)
    return render(request,'blog/edit.html',{'form':form})
  else:
    return HttpResponseRedirect("/login/")
  
 # addpost
def add_post(request):
  if request.user.is_authenticated:
    if request.method == 'POST':
       form = PostForm(request.POST)
       if form.is_valid():
         messages.success(request," Congratulations!! Your Post has add !!")

         title=form.cleaned_data['title']
         description=form.cleaned_data['description']  
         ap=Post(title=title,description=description)
         ap.save()  
         form=PostForm()
    else:
       form=PostForm()
    return render(request,'blog/addpost.html',{'form':form})
  else:
    return HttpResponseRedirect("/login/")
     


# delete
def delete(request,id):
  if request.user.is_authenticated:
    dele = Post.objects.get(id=id)
    dele.delete()
    return  HttpResponseRedirect('/dashbord/')
  else:
   return  HttpResponseRedirect('/login/')
    

newsapp/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container">
<h1>About</h1>

    <p class="col-md-8 fs-5">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
    <p class="col-md-8 fs-5"> Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
    Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
    </p>
   
</div>
{% endblock %}

newsapp/templates/blog/addpost.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container my-5">
   

<h2 class="text-center"><span class="border-bottom"> Dashboard/Addpost</span>
   </h2>
{% if messages %}
{% for message in messages %}
<h5 {% if message.tags %} class="alert alert-{{message.tags}} text-center mt-3 " {% endif %}>{{message}}</h5>
{% endfor %}
{% endif %}


    <div class="row">
        <div class="col-sm-6 offset-sm-3">
    <form  action="" method="POST" novalided>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{%  url 'dashbord' %}" class="btn btn-danger">Cancel</a>

    </form>
        </div>
    </div>
</span>  
{% endblock %}

newsapp/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   {%load static%}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'blog/navbar.html' %}
    <div class="container-fluid">
   
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
   {% block msg %}
   {% endblock msg %}
        </div>
      </div>
      <div class="row">
        {% block side %}
        {% endblock side%}
        {% block content %}
        {% endblock content %}
      </div>
    </div>
  
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

newsapp/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container">

<div class="row">
<div class="col-sm-6 offset-sm-3">
    <h1 >Contact</h1>
    <hr>
<form method="POST" action="">
 {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Submit</button>

  </form>
</div>
</div>  
</div>
{% endblock %}
{% comment %} <div class="mb-3">
  <label for="" class="form-label">Name</label>
  <input type="text" class="form-control" >
</div>
<div class="mb-3">
  <label for="" class="form-label">Password</label>
  <input type="password" class="form-control" >
</div>
<div class="mb-3">
    <label for="" class="form-label">Address</label>
    <input type="text" class="form-control">
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Message</label>
    <textarea class="form-control"id="floatingTextarea2"></textarea>
</div> {% endcomment %}

newsapp/templates/blog/dashbord.html
{% extends "blog/base.html" %}
{% load static %}
<div class="container ">
    <div class="row ">
{% block msg %}
{% if messages %}
{% for message in messages %}
<p {% if message.tag %} class="alert alert-{{message.tag}}" {% endif %}>{{message}}</p>
{% endfor %}
{% endif %}
{% endblock msg %}


{% block side %}
 <div class="col-sm-2 text-white my-5 text-center">
    <h3>Profile</h3>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
</div>
{% endblock side %}

{% block content %}
<div class="col-sm-10 my-5">
    <h1 >Dashboard</h1>
    <hr>
    <a href="{% url 'addpost' %}" class="btn btn-success mb-3"> Add Post</a>
    <table class="table  bg-light">
        <h4 class="alert alert-success text-center">Show Post Information</h4>
        {% if posts %}
        <thead>
            <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>

        </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <td>{{post.id}}</td>
                <td>{{post.title}}</td>
                <td>{{post.description}}</td>
                <td><a href ="{% url 'edit' post.id %}"class="btn btn-warning" type="submit">Edit</a></td>
                {% if perms.newsblog.delete_post %}
                <td><a href ="{% url 'delete' post.id %}"class="btn btn-danger" type="submit">Delete</a></td>
               {% endif %}
            </tr>
            {% endfor %}
        </tbody>          
    </table>
    {% else%}
    <h4 class="alert alert-danger text-center"> NO Data</h4>
    {% endif %}
</div>
    </div>
</div>
{% endblock %}

newsapp/templates/blog/edit.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container my-5">
    <div class="row">
<h2 class="text-center">Dashboard/Update</h2>
    <div class="col-sm-6 offset-sm-3">
    <form  action="" method="POST" novalided>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update" class="btn btn-success">


    <a href="{%  url 'dashbord' %}" class="btn btn-danger">Cancel</a>

</form>
</div>
    </div>
</div>
{% endblock %}

newsapp/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container">
<h1>Home</h1>

<div class="container-fluid py-5">

  {% for post in posts %}
    <h3 class="display-6 fw-bold mb-3">{{post.title}}</h3>

    <p class="col-md-8 fs-6">{{post.description}}</p>
    <button class="btn btn-primary  btn-lg" type="button">Read More</button>
    <hr>
  {% endfor %}
  </div>
</div>
{% endblock %}

newsapp/templates/blog/login.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container my-3">
<div class="row">
    <div class="col-sm-6 offset-sm-3 shadow">
    <h1>Login</h1>
<hr>
    <form method="POST" action="">
        {% csrf_token%}
       {% for form in form %}
       <div class="form-group">
       {{form.label_tag}}{{form}}{{form.errors|striptags}}
       </div>
       {% endfor %}
       <input type="submit" class="btn btn-primary my-3" value="Login">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors%}
        <p class="alert  alert-warning">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
    

    </div>
</div>
</div>
{% endblock %}

newsapp/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light "style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashbord' %}">Dashboard</a>
          </li>
          {% if not request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}

         
          <li class="nav-item">
            <form method="POST" action ="{% url 'logout' %}">
              {% csrf_token %}
              <button class="btn btn-$blue-200 " type="submit">Logout</button>
            </form>
          </li>
          {% endif %}
      
        </ul>
      </div>
    </div>
  </nav>

newsapp/templates/blog/signup.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-sm-6  offset-sm-3 shadow">
    <h1>SignUp</h1>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-4"{% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}
    <form method="POST" action="" novalidate>
        {% csrf_token %}
        {% for form in form %}
        <div class="form-group">
        {{form.label_tag}}{{form}}<small class="text-danger">{{form.errors|striptags}}</small>
         </div>
          {% endfor %}
      <input type ="submit" class="btn btn-primary my-3">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors%}
        <p class="alert alert-warning">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>

    </div>
</div>
{% endblock %}